# Change these values before running /kubex export.
mod.package=example.kubejs.mod
mod.id=example_kubejs_mod
mod.name=Example KubeJS Mod
mod.version=1.0.0
mod.description=KubeJS scripts exported by KubeX.
mod.authors=Herobrine

# Required KubeJS version range for the generated mod.
kubejs.version=[2101.7.2,)

# Add optional mod dependencies with this pattern:
# dependency.jei.version=[19.0,)
# dependency.jei.mandatory=false
# dependency.jei.ordering=AFTER
# dependency.jei.side=CLIENT